// Auto-generated from OpenAPI docs at http://localhost/api/docs.jsonopenapi
// Do not edit this file manually

import { operations } from './openapi'

export type CollectionResponses = {
  '/api/sites': operations['api_sites_get_collection']['responses'][200]['content']['application/ld+json']
  '/api/site_user_privileges': operations['api_site_user_privileges_get_collection']['responses'][200]['content']['application/ld+json']
  '/api/sites/{siteId}/user_privileges': operations['api_sites_siteIduser_privileges_get_collection']['responses'][200]['content']['application/ld+json']
  '/api/users': operations['api_users_get_collection']['responses'][200]['content']['application/ld+json']
}
