// Auto-generated from API index at http://localhost/api/index.jsonld
// Do not edit this file manually

export const API_RESOURCE_MAP = {
  analysisType: '/api/vocabulary/analysis/types',
  context: '/api/data/contexts',
  contextSample: '/api/data/context_samples',
  contextStratigraphicUnit: '/api/data/context_stratigraphic_units',
  contextType: '/api/vocabulary/context/types',
  culturalContext: '/api/vocabulary/cultural_contexts',
  decoration: '/api/vocabulary/pottery/decorations',
  functionalForm: '/api/vocabulary/pottery/functional_forms',
  functionalGroup: '/api/vocabulary/pottery/functional_groups',
  mediaObject: '/api/data/media_objects',
  mediaObjectStratigraphicUnit: '/api/media_object_stratigraphic_units',
  mediaObjectType: '/api/vocabulary/media_object/types',
  pottery: '/api/data/potteries',
  potteryAnalysis: '/api/data/analyses/potteries',
  potteryDecoration: '/api/data/pottery_decorations',
  sample: '/api/data/samples',
  sampleStratigraphicUnit: '/api/data/sample_stratigraphic_units',
  sampleType: '/api/vocabulary/sample/types',
  shape: '/api/vocabulary/pottery/shapes',
  site: '/api/data/sites',
  siteCulturalContext: '/api/data/site_cultural_contexts',
  siteUserPrivilege: '/api/admin/site_user_privileges',
  stratigraphicUnit: '/api/data/stratigraphic_units',
  surfaceTreatment: '/api/vocabulary/pottery/surface_treatments',
  user: '/api/admin/users',
} as const

export type ApiResourceKey = keyof typeof API_RESOURCE_MAP

export type ApiResourcePath =
  (typeof API_RESOURCE_MAP)[keyof typeof API_RESOURCE_MAP]
