// Auto-generated from API index at http://localhost/api/index.jsonld
// Do not edit this file manually

export const API_RESOURCE_MAP = {
  context: '/api/data/contexts',
  contextSample: '/api/data/context_samples',
  contextStratigraphicUnit: '/api/data/context_stratigraphic_units',
  mediaObject: '/api/data/media_objects',
  mediaObjectStratigraphicUnit: '/api/data/media_object_stratigraphic_units',
  pottery: '/api/data/potteries',
  potteryAnalysis: '/api/data/analyses/potteries',
  potteryDecoration: '/api/data/pottery_decorations',
  sample: '/api/data/samples',
  sampleStratigraphicUnit: '/api/data/sample_stratigraphic_units',
  site: '/api/data/sites',
  siteCulturalContext: '/api/data/site_cultural_contexts',
  siteUserPrivilege: '/api/admin/site_user_privileges',
  stratigraphicUnit: '/api/data/stratigraphic_units',
  stratigraphicUnitRelationship: '/api/data/stratigraphic_unit_relationships',
  user: '/api/admin/users',
  vocAnalysisType: '/api/vocabulary/analysis/types',
  vocContextType: '/api/vocabulary/context/types',
  vocCulturalContext: '/api/vocabulary/cultural_contexts',
  vocMediaObjectType: '/api/vocabulary/media_object/types',
  vocPotteryDecoration: '/api/vocabulary/pottery/decorations',
  vocPotteryFunctionalForm: '/api/vocabulary/pottery/functional_forms',
  vocPotteryFunctionalGroup: '/api/vocabulary/pottery/functional_groups',
  vocPotteryShape: '/api/vocabulary/pottery/shapes',
  vocPotterySurfaceTreatment: '/api/vocabulary/pottery/surface_treatments',
  vocSampleType: '/api/vocabulary/sample/types',
  vocStratigraphicUnitRelation:
    '/api/vocabulary/stratigraphic_unit/relationships',
  vocZooBone: '/api/vocabulary/zoo/bones',
  vocZooBonePart: '/api/vocabulary/zoo/bone_parts',
  vocZooTaxonomy: '/api/vocabulary/zoo/taxonomy',
  zooBone: '/api/data/zoo/bones',
  zooBoneAnalysis: '/api/data/analyses/zoo/bones',
} as const

export type ApiResourceKey = keyof typeof API_RESOURCE_MAP

export type ApiResourcePath =
  (typeof API_RESOURCE_MAP)[keyof typeof API_RESOURCE_MAP]
