// Auto-generated from API index at http://localhost/api/index.jsonld
// Do not edit this file manually

export const API_RESOURCE_MAP = {
  site: '/api/sites',
  siteUserPrivilege: '/api/site_user_privileges',
  user: '/api/users',
} as const

export type ApiResourceKey = keyof typeof API_RESOURCE_MAP

export type ApiResourcePath =
  (typeof API_RESOURCE_MAP)[keyof typeof API_RESOURCE_MAP]
